name: Deploy Cartinhas

on: [push]

jobs:
  build:
    name: Deploy Front-end
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      # This step prints the time.
      - run: echo The time was ${{ steps.hello.outputs.time }}
